# -*- coding: utf-8 -*-
"""BOJ_10610.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-T9A7TcOkJawb7vKsq-ef3NV3Yj5xY4K
"""

# 100ms

def is_30x(num_list:list) -> None:
  num_list.sort(reverse=True)
  if num_list[-1] != 0:
    print(-1)
    return
  if sum(num_list)%3 != 0:
    print(-1)
    return
  for i in num_list:
    print(i, end='')
  return

if __name__ == '__main__':
  N = list(map(int, input()))
  is_30x(N)